# Metrics Input
inputs:
    http:
        enabled: on
        mode: dev
        port: 8080
        tls:
            status: off
            pemPath: cert/server.pem
            keyPath: cert/server.key
        path: /
        api_key: ""

    log:
        enabled: on
        paths:
            - /Users/Ahmed/Space/Personal/oss/Penguin/cache/prod.log
            - /Users/Ahmed/Space/Personal/oss/Penguin/cache/dev.log

# Metrics Cache Driver
cache:
    type: memory
    enabled: on

    drivers:
        memory:
            buffer_size: 50

# Metrics Output
output:
    console:
        enabled: on

    graphite:
        enabled: on

    penguin:
        enabled: on

    prometheus:
        enabled: on

# Log configs
log:
    # Log level, it can be debug, info, warn, error, panic, fatal
    level: info
    # output can be stdout or abs path to log file /var/logs/beetle.log
    output: stdout
    # Format can be json
    format: json
