# App configs
app:
  # App name
  name: ${PENGUIN_NAME:-penguin}
  # Env mode (dev or prod)
  mode: ${PENGUIN_MODE:-prod}
  # HTTP port
  port: ${PENGUIN_PORT:-8000}
  # Hostname
  hostname: ${PENGUIN_HOSTNAME:-127.0.0.1}
  # TLS configs
  tls:
    status: ${PENGUIN_TLS_STATUS:-off}
    crt_path: ${PENGUIN_TLS_PEMPATH:-cert/server.crt}
    key_path: ${PENGUIN_TLS_KEYPATH:-cert/server.key}

  # Global timeout
  timeout: ${PENGUIN_TIMEOUT:-50}

  # API Key
  api_key: ${PENGUIN_API_KEY:-xxxx-xxxx-xxxx-xxxx}

  # Log configs
  log:
    # Log level, it can be debug, info, warn, error, panic, fatal
    level: ${PENGUIN_LOG_LEVEL:-info}
    # Output can be stdout or abs path to log file /var/logs/penguin.log
    output: ${PENGUIN_LOG_OUTPUT:-/var/logs/penguin.log}
    # Format can be json
    format: ${PENGUIN_LOG_FORMAT:-json}
