version: '3'

services:
  penguin:
    image: 'clivern/penguin:release-v0.0.2'
    ports:
      - "8000:8000"
    command: '/app/penguin run -c /app/configs/config.yml'
    volumes:
      - './configs/:/app/configs'
    restart: unless-stopped
